### ISSUE TITLE
Could you update this repository?

### ISSUE THREAD

**Issue by Opdoop** [fursovia/dilma#1]
I wish to use `dilma` as a sentence-level attack to test the robustness of my model. I noticed that your new arVix has an `anonymous github` link and the new version seems to increase more functions(e.g. compatible with `textattack`). But `anonymous github` doesn't support downloading or cloning. Could you, by any chance, upload the new code to github? I appreciate your response.

**Comment by macksjeremy** [comment]
It's definitely a shame that it's not on the main github. I was able to download it with this, https://gist.github.com/12f23eddde/afaf4f6af4608f42b3721cef5e26260a . Putting it on normal github would save the creator of anonymous-github a lot of money.

**Comment by fursovia** [comment]
Hi! Sorry for the delayed response. The latest code is here https://github.com/fursovia/dilma_research

**Comment by macksjeremy** [comment]
Thanks so much! Is this identical to what's on the anonymous github?

**Comment by fursovia** [comment]
Yes. As I remember, you should also check [this branch](https://github.com/fursovia/dilma_research/tree/adv_training) for adversarial training
